#!/bin/sh
#
# @name Gazebo alexis
# @type Fixedwing
#

. ${R}etc/init.d/rc.fw_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=alexis}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 0
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 0

param set-default SENS_EN_ARSPDSIM 1
